//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFiveP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int question_id { get; set; }
        public string question_content { get; set; }
        public Nullable<System.DateTime> question_dateCreate { get; set; }
        public Nullable<System.DateTime> question_dateEdit { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<bool> question_activate { get; set; }
        public string question_title { get; set; }
        public Nullable<int> question_totalAnswer { get; set; }
        public Nullable<int> question_totalComment { get; set; }
        public Nullable<int> question_view { get; set; }
        public Nullable<int> question_totalRate { get; set; }
        public Nullable<int> question_medalCalculator { get; set; }
        public Nullable<bool> question_recycleBin { get; set; }
        public Nullable<bool> question_userStatus { get; set; }
        public Nullable<int> question_popular { get; set; }
        public Nullable<bool> question_admin_recycleBin { get; set; }
    
        public virtual User User { get; set; }
    }
}
